#!/usr/bin/env python3
"""Convert a PNG to an RGB565 C header for TFT_eSPI pushImage()."""
import sys
from pathlib import Path

from PIL import Image


def rgb565(r: int, g: int, b: int) -> int:
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)


def main() -> None:
    if len(sys.argv) != 4:
        sys.exit(f"usage: {sys.argv[0]} <in.png> <out.h> <array_name>")

    src, dst, name = Path(sys.argv[1]), Path(sys.argv[2]), sys.argv[3]

    img = Image.open(src)
    if img.mode in ("RGBA", "LA", "P"):
        # Composite transparency onto black
        bg = Image.new("RGBA", img.size, (0, 0, 0, 255))
        img = Image.alpha_composite(bg, img.convert("RGBA"))
    img = img.convert("RGB")

    w, h = img.size
    pixels = [rgb565(*img.getpixel((x, y))) for y in range(h) for x in range(w)]

    lines = [
        "// Auto-generated by scripts/png_to_rgb565.py from " + src.name,
        "// RGB565, row-major, for TFT_eSPI pushImage()",
        "#pragma once",
        "#include <pgmspace.h>",
        "",
        f"constexpr int16_t {name.upper()}_W = {w};",
        f"constexpr int16_t {name.upper()}_H = {h};",
        f"const uint16_t {name}[{w * h}] PROGMEM = {{",
    ]
    for i in range(0, len(pixels), 12):
        chunk = ", ".join(f"0x{p:04X}" for p in pixels[i:i + 12])
        lines.append(f"    {chunk},")
    lines.append("};")
    dst.write_text("\n".join(lines) + "\n")
    print(f"{src.name} ({w}x{h}) -> {dst} ({w * h * 2} bytes)")


if __name__ == "__main__":
    main()
