#!/usr/bin/env python3
"""Convert a simple sheet music text file to a C melody[] array for main.cpp.

Sheet music format (one note per line):
    <note> <duration>

Note names:
    C D E F G A B  (natural)
    C# Db D# Eb F# Gb G# Ab A# Bb B#  (sharps/flats)
    R  (rest / silence)
    Octave appended directly: C4, G#3, Bb5

Duration codes:
    w   whole        (4 beats)
    h   half         (2 beats)
    q   quarter      (1 beat)
    e   eighth       (0.5 beats)
    s   sixteenth    (0.25 beats)
    w.  dotted whole (6 beats)
    h.  dotted half  (3 beats)
    q.  dotted quarter (1.5 beats)
    e.  dotted eighth (0.75 beats)

Example file (Happy Birthday):
    D4 q
    D4 q
    E4 h
    D4 h
    G4 h
    F#4 w

Usage:
    python3 scripts/sheet_music_to_melody.py assets/happy_birthday.txt --bpm 120
    python3 scripts/sheet_music_to_melody.py assets/happy_birthday.txt --bpm 100 --var my_melody
"""

import argparse
import sys
from pathlib import Path

# Frequency table: note name (no octave) -> semitone offset from C
SEMITONES = {
    "C": 0, "C#": 1, "DB": 1,
    "D": 2, "D#": 3, "EB": 3,
    "E": 4, "FB": 4,
    "F": 5, "F#": 6, "GB": 6,
    "G": 7, "G#": 8, "AB": 8,
    "A": 9, "A#": 10, "BB": 10,
    "B": 11, "CB": 11, "B#": 0,
}

DURATION_BEATS = {
    "w": 4.0,
    "h": 2.0,
    "q": 1.0,
    "e": 0.5,
    "s": 0.25,
    "w.": 6.0,
    "h.": 3.0,
    "q.": 1.5,
    "e.": 0.75,
}


def note_to_freq(note_str: str) -> int:
    """Convert note string like 'D4', 'F#3', 'Bb5' to Hz. Returns 0 for rests."""
    note_str = note_str.strip()
    if note_str.upper() == "R":
        return 0

    # Split accidental + letter from octave number
    # e.g. "F#4" -> note="F#", octave=4
    i = len(note_str) - 1
    while i >= 0 and (note_str[i].isdigit() or note_str[i] == "-"):
        i -= 1
    note_name = note_str[:i + 1].upper()
    octave_str = note_str[i + 1:]

    if note_name not in SEMITONES:
        raise ValueError(f"Unknown note name: '{note_str}'")
    if not octave_str:
        raise ValueError(f"Missing octave number in: '{note_str}' (e.g. use D4 not D)")

    octave = int(octave_str)
    semitone = SEMITONES[note_name]

    # MIDI note number: C4 = 60
    midi = (octave + 1) * 12 + semitone
    freq = round(440.0 * (2 ** ((midi - 69) / 12.0)))
    return freq


def beats_to_ms(beats: float, bpm: float) -> int:
    return round((beats / bpm) * 60_000)


def parse_sheet(path: Path, bpm: float) -> list[tuple[int, int]]:
    notes = []
    for lineno, raw in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
        line = raw.strip()
        if not line or line.startswith("#"):
            continue

        parts = line.split()
        if len(parts) != 2:
            raise ValueError(f"Line {lineno}: expected '<note> <duration>', got: '{line}'")

        note_str, dur_str = parts
        dur_str = dur_str.lower()

        if dur_str not in DURATION_BEATS:
            raise ValueError(f"Line {lineno}: unknown duration '{dur_str}'. Valid: {list(DURATION_BEATS)}")

        freq = note_to_freq(note_str)
        ms = beats_to_ms(DURATION_BEATS[dur_str], bpm)
        notes.append((freq, ms))

    return notes


def render_c_array(notes: list[tuple[int, int]], var_name: str) -> str:
    lines = [
        f"// Auto-generated by scripts/sheet_music_to_melody.py",
        f"struct Note {{ uint16_t freq; uint16_t ms; }};",
        f"const Note {var_name}[] = {{",
    ]
    for i in range(0, len(notes), 4):
        chunk = notes[i:i + 4]
        row = ", ".join(f"{{{f}, {m}}}" for f, m in chunk)
        lines.append(f"    {row},")
    lines.append("};")
    lines.append(f"constexpr size_t {var_name.upper()}_LEN = sizeof({var_name}) / sizeof({var_name}[0]);")
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description="Sheet music text → C melody[] array")
    parser.add_argument("input", help="Sheet music .txt file")
    parser.add_argument("--bpm", type=float, default=120.0, help="Tempo in BPM (default: 120)")
    parser.add_argument("--var", default="melody", help="C variable name (default: melody)")
    args = parser.parse_args()

    src = Path(args.input)
    if not src.exists():
        sys.exit(f"File not found: {src}")

    try:
        notes = parse_sheet(src, args.bpm)
    except ValueError as e:
        sys.exit(f"Parse error: {e}")

    print(render_c_array(notes, args.var))


if __name__ == "__main__":
    main()
