#!/usr/bin/env python3
"""Convert a TTF to an Adafruit GFX font header (TFT_eSPI FreeFont compatible).

Renders glyphs 0x20-0x7E in 1-bit (no anti-aliasing) — suited to pixel fonts.
"""
import re
import sys
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

PAD = 8  # padding around render canvas


def render_glyph(font: ImageFont.FreeTypeFont, ch: str, size: int):
    """Render one glyph, return (bitmap_rows, w, h, x_off, y_off, x_adv)."""
    canvas = Image.new("L", (size * 4, size * 4), 0)
    draw = ImageDraw.Draw(canvas)
    draw.fontmode = "1"  # disable anti-aliasing
    origin = (size + PAD, size + PAD)
    draw.text(origin, ch, font=font, fill=255)

    ascent, _ = font.getmetrics()
    baseline_y = origin[1] + ascent
    x_adv = round(font.getlength(ch))

    bbox = canvas.getbbox()
    if bbox is None:  # space etc.
        return [], 0, 0, 0, 0, x_adv

    x0, y0, x1, y1 = bbox
    w, h = x1 - x0, y1 - y0
    px = canvas.load()
    rows = [[1 if px[x0 + x, y0 + y] else 0 for x in range(w)] for y in range(h)]
    return rows, w, h, x0 - origin[0], y0 - baseline_y, x_adv


def main() -> None:
    if len(sys.argv) != 4:
        sys.exit(f"usage: {sys.argv[0]} <in.ttf> <out.h> <size_px>")

    src, dst, size = Path(sys.argv[1]), Path(sys.argv[2]), int(sys.argv[3])
    font = ImageFont.truetype(str(src), size)
    name = re.sub(r"\W", "", src.stem) + str(size) + "px"

    bitmap_bytes: list[int] = []
    glyphs = []  # (offset, w, h, xAdv, dx, dy, char)
    for code in range(0x20, 0x7F):
        rows, w, h, dx, dy, x_adv = render_glyph(font, chr(code), size)
        offset = len(bitmap_bytes)
        bits = [b for row in rows for b in row]
        for i in range(0, len(bits), 8):
            chunk = bits[i:i + 8] + [0] * (8 - len(bits[i:i + 8]))
            bitmap_bytes.append(int("".join(map(str, chunk)), 2))
        glyphs.append((offset, w, h, x_adv, dx, dy, chr(code)))

    ascent, descent = font.getmetrics()
    y_advance = ascent + descent

    lines = [
        f"// Auto-generated by scripts/ttf_to_gfx.py from {src.name} at {size}px",
        "#pragma once",
        "",
        f"const uint8_t {name}Bitmaps[] PROGMEM = {{",
    ]
    for i in range(0, len(bitmap_bytes), 12):
        chunk = ", ".join(f"0x{b:02X}" for b in bitmap_bytes[i:i + 12])
        lines.append(f"    {chunk},")
    lines += ["};", "", f"const GFXglyph {name}Glyphs[] PROGMEM = {{"]
    for offset, w, h, x_adv, dx, dy, ch in glyphs:
        safe = ch if ch not in ("\\", "*/") else "esc"
        lines.append(
            f"    {{ {offset:5d}, {w:3d}, {h:3d}, {x_adv:3d}, {dx:4d}, {dy:5d} }}, // '{safe}'"
        )
    lines += [
        "};",
        "",
        f"const GFXfont {name} PROGMEM = {{",
        f"    (uint8_t *){name}Bitmaps,",
        f"    (GFXglyph *){name}Glyphs,",
        f"    0x20, 0x7E, {y_advance},",
        "};",
    ]
    dst.write_text("\n".join(lines) + "\n")
    total = len(bitmap_bytes) + len(glyphs) * 7 + 16
    print(f"{src.name} @{size}px -> {dst} (~{total} bytes, font name: {name})")


if __name__ == "__main__":
    main()
